#!/usr/bin/env python3
"""Writes coop/common/GameIds.inc from the game's headers: items (z64item.h), actors (tables/actor_table.h) and
scenes with the index of their entrance table (tables/scene_table.h, z64scene.h). Run it from anywhere:

    python coop/tools/gen_game_ids.py

The mods of the co-op server name the game's things with these lists ("MASK_BUNNY", "EN_DODONGO",
"SOUTH_CLOCK_TOWN"); the game checks every value at compile time (mm/2s2h/Coop/Mods/GameIdsCheck.cpp), so a list
that falls behind the game does not build. Afterwards regenerate the reference:

    build/coop/Release/2ship-coop-server.exe --mod-docs coop/docs/mods
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INCLUDE = ROOT / "mm" / "include"
OUT = ROOT / "coop" / "common" / "GameIds.inc"


def enum_values(body, prefix):
    """(name without prefix, value) of an enum's body, following explicit `= value` assignments."""
    out = []
    value = 0
    for line in body.splitlines():
        line = re.sub(r"/\*.*?\*/", "", line).split("//")[0].strip().rstrip(",")
        match = re.match(r"^(" + prefix + r"\w+)\s*(?:=\s*(\w+))?$", line)
        if not match:
            continue
        if match.group(2):
            value = int(match.group(2), 0)
        out.append((match.group(1)[len(prefix):], value))
        value += 1
    return out


def enum_body(text, marker):
    """The body of the enum that contains `marker` (one of its values, or its `typedef enum Name`)."""
    at = text.index(marker)
    start = text.rindex("typedef enum", 0, at + len("typedef enum"))
    return text[text.index("{", start) + 1:text.index("}", start)]


def split_args(text):
    """Macro arguments, minding nested parentheses and string literals."""
    args, depth, current, quoted = [], 0, "", False
    for ch in text:
        if ch == '"':
            quoted = not quoted
        if not quoted and ch == "(":
            depth += 1
        elif not quoted and ch == ")":
            depth -= 1
        if ch == "," and depth == 0 and not quoted:
            args.append(current.strip())
            current = ""
        else:
            current += ch
    args.append(current.strip())
    return args


def table_rows(path, macros):
    """(macro, args) of every line of an X-macro table, in order."""
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.search(r"\b(" + "|".join(macros) + r")\s*\((.*)\)\s*(//.*)?$", line.strip())
        if match:
            rows.append((match.group(1), split_args(match.group(2))))
    return rows


def main():
    lines = ["// Generated by coop/tools/gen_game_ids.py from the game's headers. Do not edit: run the script again.",
             "// COOP_ITEM(name, id)   COOP_ACTOR(name, id, title)",
             "// COOP_SCENE(key, decompName, sceneId, entranceScene, title): key is the name of its entrance table",
             ""]

    items = enum_values(enum_body((INCLUDE / "z64item.h").read_text(encoding="utf-8"), "typedef enum ItemId"), "ITEM_")
    count = 0
    for name, value in items:
        if re.fullmatch(r"[0-9A-F]{2}", name) or name == "NONE":
            continue  # slots of the enum without a name of their own
        lines.append(f"COOP_ITEM({name}, 0x{value:02X})")
        count += 1
    lines.append("")
    summary = [f"{count} items"]

    index = 0
    count = 0
    for macro, args in table_rows(INCLUDE / "tables" / "actor_table.h",
                                  ["DEFINE_ACTOR_INTERNAL", "DEFINE_ACTOR_UNSET", "DEFINE_ACTOR"]):
        if macro != "DEFINE_ACTOR_UNSET" and args[1] != "ACTOR_EN_COOP_PUPPET":  # the co-op's own: never a mod's
            lines.append(f"COOP_ACTOR({args[1][len('ACTOR_'):]}, 0x{index:03X}, {args[4]})")
            count += 1
        index += 1
    lines.append("")
    summary.append(f"{count} actors")

    scene_header = (INCLUDE / "z64scene.h").read_text(encoding="utf-8")
    entrances = dict(enum_values(enum_body(scene_header, "ENTR_SCENE_MAYORS_RESIDENCE"), "ENTR_SCENE_"))
    index = 0
    count = 0
    for macro, args in table_rows(INCLUDE / "tables" / "scene_table.h", ["DEFINE_SCENE_UNSET", "DEFINE_SCENE"]):
        if macro == "DEFINE_SCENE":
            key = args[6]
            if key not in entrances:
                sys.exit(f"scene {args[1]}: unknown entrance scene {key}")
            lines.append(f"COOP_SCENE({key}, {args[1][len('SCENE_'):]}, 0x{index:02X}, 0x{entrances[key]:02X}, {args[8]})")
            count += 1
        index += 1
    summary.append(f"{count} scenes")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUT}: " + ", ".join(summary))


if __name__ == "__main__":
    main()
